name: Update files on GitHub
description: Update (i.e. commit and push) files on GitHub
author: alexesprit
inputs:
  # Required
  commit-msg:
    description: Commit message
    requried: true

  file-path:
    description: Path to file(s) or glob pattern
    requried: true

  github-token:
    description: GitHub token
    requried: true

  # Optional
  branch:
    description: Branch name
    requried: false

  allow-dot:
    description: Allow glob patterns to match entries that begin with a period
    default: false
    required: false

  allow-removing:
    desciption: Allow to remove file
    default: false
    required: false

  committer-name:
    description: The name of the author (or committer) of the commit
    default: 'github-actions[bot]'
    required: false

  committer-email:
    description: The email of the author (or committer) of the commit
    default: 'github-actions[bot]@users.noreply.github.com'
    required: false

runs:
  using: node16
  main: dist/index.js
branding:
  icon: git-commit
  color: gray-dark
