name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Run lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install
      - run: npm run lint
      - run: npm test
